INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('ilsun.lee','il2255','Ilsun Lee','29','3251 Romano Street, Malden, MA 02148','il2255@yahee.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('meng.da','md3356','Meng Da','22','1762 Harley Vincent Drive, Brecksville, OH 44141','md3356@googla.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('jacob.smith','js5683','Jacob Smith','25','2414 Oakmound Road, Chicago, IL 60605','jacob.s@outlok.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('mason.johnson','masonJ2039','Mason Johnson','24','3907 Pritchard Court, Oronoco, MN 55960','johnson.m@googla.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('ethan.thomas','Thomas3957','Ethan Thomas','23','1617 Charles Street, Ypsilanti, MI 48198','et3567@yahee.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('sophia.lee','thisisSophia','Sophia Lee','28','1304 Ryder Avenue, Bellevue, WA 98007','lee.s123@hetmail.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('emma.lopez','Lopez8093','Emma Lopez','30','2406 White Lane, Macon, GA 31206','elopez@hetmail.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('isabella.hill','LeoniaPark80','Isabella Hill','31','1081 Timber Oak Drive, Lubbock, TX 79401','Isa.Hill@colombie.edu','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('olivia.nelson','Eminem8090','Olivia Nelson','24','2078 Hardesty Street, Albany, NY 12207','on2345@bern.edu','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('aiden.perez','NYRules7629','Aiden Parez','22','1778 Paradise Lane Chino, CA 91710','parez.aiden.56@yahee.com','0');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('yahoo_web_hr','FsGKQe7s','Yahoo_web_HR','','3339 Lowndes Hill Park Road, Bakersfield, CA 93307','hr_web@yahoo.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('yahoo_marketing','MNwVu3fy','Yahoo_marketing_HR','','3339 Lowndes Hill Park Road, Bakersfield, CA 93307','hr_market@yahoo.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('google_IT','sDef2bdT','google_IT','','4178 Robinson Lane, Delaware, OH 43015','hr_it@google.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('google_marketing','D6F9yUNP','google_marketing','','4178 Robinson Lane, Delaware, OH 43015','hr_marketing@google.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('chase','DYaPMrVm','chase','','4928 Ingram Street, Kettering, OH 45429','recruit@chase.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('bloomberg','ct23my9h','bloomberg','','387 Dale Avenue, Seattle, WA 98109','humanresource@bloomberg.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('apple','SDkBpp2M','apple','','635 Hide A Way Road, Orlando, FL 32810','hr@appler.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('facebook','AHUMSM6h','facebook','','2078 Still Street, Norwalk, OH 44857','HR@facebook.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('ibm','rFNvsKPG','IBM','','1977 Clement Street, Atlanta, GA 30337','HR@ibm.com','1');
INSERT INTO Users (userID,password,name,age,address,email,status) VALUES ('ny_hospital','brhyTX9q','nyhospital','','4712 Simpson Avenue, New York NY 10024','ny_hospital_hr@nyhospital.org','1');
