INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('Actively looking for a job','Software Engineer','Software Developer','ilsun.lee');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('Actively looking for an internship','Software Developer','Student','meng.da');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('Looking for an internship','Network Administrator','Student','jacob.smith');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('Looking for a full time position','Database Administrator','Student','mason.johnson');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('Looking for an additional part time position','Registered Nurse','Registered Nurse','ethan.thomas');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('Not currently looking for a job','General Manager','Manager','sophia.lee');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('Not currently looking for a job','Consultant','Consultant','emma.lopez');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('Looking for an intership position','Quantitative Analyst','Student','isabella.hill');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('Looking for a new job','Systems Engineer','Software Engineer','olivia.nelson');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('Seeking a new position','Business Analyst','Consultant','aiden.perez');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('','','','yahoo_web_hr');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('','','','yahoo_marketing');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('','','','google_IT');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('','','','google_marketing');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('','','','chase');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('','','','bloomberg');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('','','','apple');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('','','','facebook');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('','','','ibm');
INSERT INTO job_seeker (currentStatus,preferJob,currentJob,userID) VALUES ('','','','ny_hospital');

