DROP TABLE Reference_Recommend;
DROP TABLE Job_Require_Skill;
DROP TABLE Resume_Have_Skill;
DROP TABLE JobSeeker_Apply_Job;
DROP TABLE Resume_Have_WorkExperience;
DROP TABLE Resume_Post;
DROP TABLE Job_Post;
DROP TABLE Skill;
DROP TABLE Job_Seeker;
DROP TABLE Employer;
DROP TABLE Users; 
PURGE recyclebin;
select * from tab;
